apiVersion: v1
kind: ConfigMap
metadata: { name: flag-service-config, namespace: flags }
data:
  PORT: "8002"
  # DNS entre namespaces: <service>.<namespace>.svc.cluster.local
  AUTH_SERVICE_URL: "http://auth-service.auth.svc.cluster.local:8001"
