apiVersion: v1
kind: ConfigMap
metadata: { name: targeting-service-config, namespace: targeting }
data:
  PORT: "8003"
  # DNS entre namespaces: <service>.<namespace>.svc.cluster.local
  AUTH_SERVICE_URL: "http://auth-service.auth.svc.cluster.local:8001"
